---
title: "Exercise 2 -- Matrices"
format: 
    html:
      embed-resources: true
editor: source
---

## Exercise 1. Matrices


1. Suppose

 $$A = \begin{pmatrix}
1& 1 & 3 \\
 5& 2 &6  \\
-2 & -1 & -3
\end{pmatrix}$$

<div style = "margin-left: 2cm">
  (a) Check that $A^3 = 0$ where $0$ is a $3 \times 3$ matrix with every entry equal to 0.

  (b) Replace the third column of $A$ by the sum of the second and third columns.
</div>

2. Create the following matrix B with 15 rows:

$$B = \begin{pmatrix}
10 & -10 & 10 \\
10 & -10 & 10 \\
\dots & \dots & \dots \\
10 & -10 & 10 \\
\end{pmatrix}$$


<div style = "margin-left: 2cm">
Calculate the $3 \times 3$ matrix $B^TB$. <br>
(Look at the help for crossprod().)
</div>

3. Create a $6 \times 6$ matrix **matE** with every entry equal to $0$. Check what the functions row() and col() return when
applied to matE. Hence create the $6 \times 6$ matrix:

$$\begin{bmatrix}
0 & 1 & 0 & 0 & 0 &  0\\
1 & 0 & 1 & 0 & 0 & 0 \\
0 & 1 & 0 & 1 & 0 & 0 \\
 0& 0 & 1 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 & 0 & 1 \\
0 &  0& 0 & 0 & 1 & 0 \\
\end{bmatrix}$$




4. Look at the help for the function outer(). Hence create the following patterned matrix:

$$\begin{bmatrix}
0 & 1 & 2 & 3 & 4\\
1 & 2 & 3 & 4 & 5\\
2 & 3 & 4 & 5 & 6\\
3 & 4 & 5 & 6 & 7\\
4 & 5 & 6 & 7 & 8\\
\end{bmatrix}$$

<p style="page-break-before:always"> </p>

5. Create the following patterned matrices. In each case, your solution should make use of the special form
of the matrix. This means that the solution should easily generalize to creating a larger matrix with the
same structure and should not involve typing in all the entries in the matrix.
(a)

$$\begin{bmatrix}
0 & 1 & 2 & 3 & 4\\
1 & 2 & 3 & 4 & 0\\
2 & 3 & 4 & 0 & 1\\
3 & 4 & 0 & 1 & 2\\
4 & 0 & 1 & 2 & 3\\
\end{bmatrix}$$

(b)

\begin{bmatrix}
0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9\\
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 0\\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots\\

8 & 9 & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7\\
9 & 0 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8\\
\end{bmatrix}


(c)

$$\begin{bmatrix}
0 & 8 & 7 & 6 & 5 & 4 & 3 & 2 & 1\\
1 & 0 & 8 & 7 & 6 & 5 & 4 & 3 & 2\\
2 & 1 & 0 & 8 & 7 & 6 & 5 & 4 & 3\\
3 & 2 & 1 & 0 & 8 & 7 & 6 & 5 & 4\\
4 & 3 & 2 & 1 & 0 & 8 & 7 & 6 & 5\\
5 & 4 & 3 & 2 & 1 & 0 & 8 & 7 & 6\\
6 & 5 & 4 & 3 & 2 & 1 & 0 & 8 & 7\\
7 & 6 & 5 & 4 & 3 & 2 & 1 & 0 & 8\\
8 & 7 & 6 & 5 & 4 & 3 & 2 & 1 & 0\\
\end{bmatrix}$$

<p style="page-break-before:always"> </p>

6. Solve the following system of linear equations in five unknowns

$$\begin{matrix}
x_1 &+ & 2x_2 &+ & 3x_3 &+ & 4x_4 &+ & 5x_5 &= &7\\
2x_1 &+ & x_2 &+ & 2x_3 &+ & 3x_4 &+ & 4x_4 &= &-1\\
3x_1 &+ & 2x_2 &+ & x_3 &+ & 2x_4 &+ & 3x_4 &= &-3\\
4x_1 &+ & 3x_2 &+ & 2x_3 &+ & x_4 &+ & 2x_4 &= &5\\
5x_1 &+ & 4x_2 &+ & 3x_3 &+ & 2x_4 &+ & x_4 &= &17\\
\end{matrix}$$
 
<div style="margin-left:2cm">
by considering an appropriate matrix equation $Ax = y$.
Make use of the special form of the matrix A.
<br> The method used for the solution should easily generalise to
a larger set of equations where the matrix $A$ has the same structure; hence the solution should not involve
typing in every number of $A$.
</div>

7. Create a $6 \times 10$ matrix of random integers chosen from 1, 2, ... , 10 by executing the following two lines
of code:

<div style="margin-left:2cm">
```
set.seed(75)
aMat <- matrix( sample(10, size=60, replace=T), nr=6)
```

(a) Find the number of entries in each row which are greater than 4.

(b) Which rows contain exactly two occurrences of the number seven?

(c) Find those pairs of columns whose total (over both columns) is greater than 75. The answer should be a matrix with two columns. So, for example, the row $(1,2)$ in the output matrix means that the sum
of columns 1 and 2 in the original matrix is greater than 75. Repeating a column is permitted. So, for example, the final output matrix could contain the rows $(1,2)$, $(2,1)$ and $(2,2)$.
What if repetitions are not permitted? Then, only $(1,2)$ from $(1,2), (2,1)$, and $(2,2)$ would be permitted.
</div>

8. Calculate
<div style="margin-left:3cm">
(a)
$\displaystyle \sum_{i=1}^{20} \sum_{j=1}^5 \frac{i^4}{(3+j)}$

(b)
$\displaystyle \sum_{i=1}^{20} \sum_{j=1}^5 \frac{i^4}{(3 + ij)}$

(c)
$\displaystyle \sum_{i=1}^{10} \sum_{j=1}^{i} \frac{i^4}{(3+ij)}$

</div>
